/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary-dim": "#971b4e",
        "surface-container": "#ffe0ed",
        "surface": "#fff4f6",
        "on-secondary-fixed": "#5d006d",
        "outline-variant": "#d59db9",
        "primary-container": "#ff709f",
        "on-secondary-container": "#7c0091",
        "surface-dim": "#ffc4e1",
        "surface-container-highest": "#ffd0e6",
        "inverse-primary": "#fd6c9c",
        "background": "#fff4f6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#f06292",
        "tertiary-fixed-dim": "#eec540",
        "secondary-container": "#fcbcff",
        "on-surface": "#492138",
        "error-container": "#f74b6d",
        "tertiary-container": "#fdd34d",
        "on-primary": "#ffeff1",
        "on-error": "#ffefef",
        "on-secondary": "#ffeefb",
        "on-surface-variant": "#7b4d66",
        "on-tertiary": "#fff2d4",
        "tertiary-fixed": "#fdd34d",
        "on-error-container": "#510017",
        "on-primary-container": "#4c0022",
        "surface-container-low": "#ffecf3",
        "surface-bright": "#fff4f6",
        "error-dim": "#a70138",
        "primary": "#a7295a",
        "inverse-surface": "#220216",
        "secondary": "#9720ab",
        "on-tertiary-container": "#5c4900",
        "on-background": "#492138",
        "surface-variant": "#ffd0e6",
        "on-primary-fixed-variant": "#5d002b",
        "surface-tint": "#a7295a",
        "inverse-on-surface": "#c38da9",
        "on-primary-fixed": "#000000",
        "tertiary-dim": "#624d00",
        "on-tertiary-fixed-variant": "#675200",
        "surface-container-high": "#ffd8e9",
        "on-secondary-fixed-variant": "#8a0b9f",
        "tertiary": "#705900",
        "secondary-fixed-dim": "#f9a7ff",
        "secondary-dim": "#89089e",
        "secondary-fixed": "#fcbcff",
        "outline": "#9a6882",
        "primary-fixed": "#ff709f",
        "on-tertiary-fixed": "#463600",
        "error": "#b41340"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"}
    },
  },
  plugins: [],
}
